### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by jdebache** [Merck/rdf2x#6]
Hello, I have a 8 GB RDF file to convert and I keep getting this error:
```
2020-10-25 20:51:23 INFO  EntitySchemaCollector:74 - Counting instances by type
[Stage 7:================>                                          (2 + 1) / 7]2020-10-25 21:13:17 ERROR ActorSystemImpl:66 - Uncaught fatal error from thread [sparkDriverActorSystem-akka.remote.default-remote-dispatcher-19] shutting down ActorSystem [sparkDriverActorSystem]
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at akka.dispatch.Envelope$.apply(AbstractDispatcher.scala:28)
        at akka.actor.Cell$class.sendMessage(ActorCell.scala:290)
        at akka.actor.ActorCell.sendMessage(ActorCell.scala:369)
        at akka.actor.RepointableActorRef.$bang(RepointableActorRef.scala:166)
        at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:61)
        at akka.actor.LightArrayRevolverScheduler$$anon$2$$anon$1.run(Scheduler.scala:242)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2020-10-25 21:13:32 ERROR Executor:74 - Managed memory leak detected; size = 1155085511 bytes, TID = 51
2020-10-25 21:13:32 ERROR Executor:95 - Exception in task 2.0 in stage 7.0 (TID 51)
```

The command I run is `mvn -e exec:java -Dspark.driver.memory=16g -Dexec.args="convert --input.file '/mnt/e/ontologies/permid/' --db.url \"jdbc:postgresql://localhost:5559/permid\" --db.user **** --db.password **** --db.schema public --output.target DB"`

I'm not a Java guy, and I cannot find a way of disabling that automatic memory leak detection.

**Comment by jdebache** [comment]
After looking at the logs a bit closer, I noticed that the `spark.driver.memory option is ignored:
```
2020-10-25 23:31:53 INFO  SparkContextProvider:59 - Getting Spark Context for config:
spark.app.name=RDF2X
spark.driver.memory=1g
```

**Comment by prihoda** [comment]
Hi @hypdeb, thanks for the heads up, looks like we forgot that property was overwritten by our `pom.xml` config. I removed it from there, try pulling the current master version and you should be able to use your command. Please let me know if that resolved your issue.

**Comment by jdebache** [comment]
Hello @prihoda,

This, or the fact that I ran `export JAVA_OPTS='-XX:GCTimeRatio=5'` seems to have solved the issue.

On an unrelated note, even though it seems like it succeeds, the shut down is not very graceful :D

```
2020-10-26 19:13:17 INFO  ConvertJob:272 - Conversion done.
2020-10-26 19:13:17 ERROR ContextCleaner:95 - Error in cleaning thread
java.lang.InterruptedException
        at java.lang.Object.wait(Native Method)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
        at org.apache.spark.ContextCleaner$$anonfun$org$apache$spark$ContextCleaner$$keepCleaning$1.apply$mcV$sp(ContextCleaner.scala:176)
        at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1181)
        at org.apache.spark.ContextCleaner.org$apache$spark$ContextCleaner$$keepCleaning(ContextCleaner.scala:173)
        at org.apache.spark.ContextCleaner$$anon$3.run(ContextCleaner.scala:68)
2020-10-26 19:13:17 ERROR Utils:95 - uncaught error in thread SparkListenerBus, stopping SparkContext
java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
        at java.util.concurrent.Semaphore.acquire(Semaphore.java:312)
        at org.apache.spark.util.AsynchronousListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(AsynchronousListenerBus.scala:66)
        at org.apache.spark.util.AsynchronousListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply(AsynchronousListenerBus.scala:65)
        at org.apache.spark.util.AsynchronousListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply(AsynchronousListenerBus.scala:65)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
        at org.apache.spark.util.AsynchronousListenerBus$$anon$1$$anonfun$run$1.apply$mcV$sp(AsynchronousListenerBus.scala:64)
        at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1181)
        at org.apache.spark.util.AsynchronousListenerBus$$anon$1.run(AsynchronousListenerBus.scala:63)
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/static/sql,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/SQL2/execution/json,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/SQL2/execution,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/SQL2/json,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/SQL2,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/static/sql,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/SQL1/execution/json,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/SQL1/execution,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/SQL1/json,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/SQL1,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/static/sql,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/SQL/execution/json,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/SQL/execution,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/SQL/json,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/SQL,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/metrics/json,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/stages/stage/kill,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/api,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/static,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/executors/threadDump/json,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/executors/threadDump,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/executors/json,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/executors,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/environment/json,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/environment,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/storage/rdd/json,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/storage/rdd,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/storage/json,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/storage,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/stages/pool/json,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/stages/pool,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/stages/stage/json,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/stages/stage,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/stages/json,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/stages,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/jobs/job/json,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/jobs/job,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/jobs/json,null}
2020-10-26 19:13:17 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/jobs,null}
2020-10-26 19:13:31 WARN  NettyRpcEndpointRef:91 - Error sending message [message = Heartbeat(driver,[Lscala.Tuple2;@3d56e4d5,BlockManagerId(driver, localhost, 34705))] in 1 attempts
org.apache.spark.rpc.RpcTimeoutException: Futures timed out after [10 seconds]. This timeout is controlled by spark.executor.heartbeatInterval
        at org.apache.spark.rpc.RpcTimeout.org$apache$spark$rpc$RpcTimeout$$createRpcTimeoutException(RpcTimeout.scala:48)
        at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:63)
        at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:59)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33)
        at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:76)
        at org.apache.spark.rpc.RpcEndpointRef.askWithRetry(RpcEndpointRef.scala:101)
        at org.apache.spark.executor.Executor.org$apache$spark$executor$Executor$$reportHeartBeat(Executor.scala:476)
        at org.apache.spark.executor.Executor$$anon$1$$anonfun$run$1.apply$mcV$sp(Executor.scala:505)
        at org.apache.spark.executor.Executor$$anon$1$$anonfun$run$1.apply(Executor.scala:505)
        at org.apache.spark.executor.Executor$$anon$1$$anonfun$run$1.apply(Executor.scala:505)
        at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1801)
        at org.apache.spark.executor.Executor$$anon$1.run(Executor.scala:505)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
        at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
        at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
        at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:107)
        at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
        at scala.concurrent.Await$.result(package.scala:107)
        at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
        ... 14 more
[WARNING] thread Thread[dispatcher-event-loop-0,5,com.merck.rdf2x.main.Main] was interrupted but is still alive after waiting at least 14996msecs
[WARNING] thread Thread[dispatcher-event-loop-0,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[dispatcher-event-loop-1,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[dispatcher-event-loop-2,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[dispatcher-event-loop-3,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[dispatcher-event-loop-4,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[dispatcher-event-loop-5,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[dispatcher-event-loop-6,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[dispatcher-event-loop-7,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[dispatcher-event-loop-8,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[dispatcher-event-loop-9,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[dispatcher-event-loop-10,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[dispatcher-event-loop-11,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[dispatcher-event-loop-12,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[dispatcher-event-loop-13,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[dispatcher-event-loop-14,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[dispatcher-event-loop-15,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[shuffle-server-0,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[sparkDriverActorSystem-scheduler-1,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[sparkDriverActorSystem-akka.actor.default-dispatcher-4,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[New I/O worker #1,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[New I/O worker #2,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[New I/O boss #3,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[New I/O worker #4,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[New I/O worker #5,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[New I/O server boss #6,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[MAP_OUTPUT_TRACKER cleanup timer,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[BLOCK_MANAGER cleanup timer,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[BROADCAST_VARS cleanup timer,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[refresh progress,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[heartbeat-receiver-event-loop-thread,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[netty-rpc-env-timeout,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[Timer-0,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[driver-heartbeater,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[shuffle-server-0,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[SparkListenerBus,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[task-result-getter-0,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[task-result-getter-1,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[task-result-getter-2,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[task-result-getter-3,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[sparkDriverActorSystem-akka.remote.default-remote-dispatcher-42,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[sparkDriverActorSystem-akka.remote.default-remote-dispatcher-43,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] NOTE: 41 thread(s) did not finish despite being asked to  via interruption. This is not a problem with exec:java, it is a problem with the running code. Although not serious, it should be remedied.
[WARNING] Couldn't destroy threadgroup org.codehaus.mojo.exec.ExecJavaMojo$IsolatedThreadGroup[name=com.merck.rdf2x.main.Main,maxpri=10]
java.lang.IllegalThreadStateException
    at java.lang.ThreadGroup.destroy (ThreadGroup.java:778)
    at org.codehaus.mojo.exec.ExecJavaMojo.execute (ExecJavaMojo.java:321)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

**Comment by jdebache** [comment]
In any case, thank you for the timely support

**Comment by prihoda** [comment]
> 
> On an unrelated note, even though it seems like it succeeds, the shut down is not very graceful :D
> 

Yup that's right, unfortunately the tool honestly hasn't been touched in three years, so it's not a priority for me anymore. I am glad when anyone finds it useful though!

**Comment by jdebache** [comment]
Original issue is fixed. Closing :) Thanks again.
