### ISSUE TITLE
Convert .ttl to JSON - throws exceptions

### ISSUE THREAD

**Issue by BoraBak** [Merck/rdf2x#7]
Running the following command:
```
mvn exec:java -Dexec.args="convert \
--input.file /Users/bora/javaproj/rdf2x/src/main/resources/test/datasets/parserTest.ttl \
--output.target JSON \
--output.folder src/main/resources/test/datasets"
```

Throws the following exceptions:
```
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------< com.merck.open:rdf2x >------------------------
[INFO] Building rdf2x 0.1.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ rdf2x ---
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/bora/.m2/repository/org/slf4j/slf4j-log4j12/1.7.10/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/bora/.m2/repository/org/slf4j/slf4j-jdk14/1.5.6/slf4j-jdk14-1.5.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/bora/.m2/repository/ch/qos/logback/logback-classic/1.1.2/logback-classic-1.1.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
2021-08-30 20:27:38 INFO  SparkContextProvider:59 - Getting Spark Context for config:
spark.app.name=RDF2X
spark.kryo.classesToRegister=com.merck.rdf2x.beans.Instance,com.merck.rdf2x.beans.Predicate,com.merck.rdf2x.beans.RelationPredicate,com.merck.rdf2x.beans.RelationRow,com.merck.rdf2x.beans.TypeID,java.util.HashMap,java.util.HashSet,com.merck.rdf2x.rdf.LiteralType,[Ljava.lang.Object;,[Lorg.apache.spark.sql.catalyst.InternalRow;,org.apache.spark.sql.catalyst.expressions.GenericInternalRow,com.merck.rdf2x.beans.IndexMap,org.apache.jena.sparql.core.Quad
spark.master=local
spark.serializer=org.apache.spark.serializer.KryoSerializer
2021-08-30 20:27:38 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2021-08-30 20:27:44 INFO  PlatformDependent:101 - Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system unstability.
2021-08-30 20:27:44 INFO  Slf4jLogger:80 - Slf4jLogger started
2021-08-30 20:27:44 INFO  Remoting:74 - Starting remoting
2021-08-30 20:27:44 INFO  Remoting:74 - Remoting started; listening on addresses :[akka.tcp://sparkDriverActorSystem@192.168.0.117:56734]
2021-08-30 20:27:44 INFO  Server:272 - jetty-8.y.z-SNAPSHOT
2021-08-30 20:27:44 INFO  AbstractConnector:338 - Started SelectChannelConnector@0.0.0.0:4040
2021-08-30 20:27:45 INFO  ConvertJob:115 - Preparing input file: src/main/resources/test/datasets/parserTest.ttl
2021-08-30 20:27:45 WARN  ElephasQuadParser:117 - Unable to guess input file format, parsing by master node only.
2021-08-30 20:27:45 INFO  ElephasQuadParser:81 - Input format is not line based, parsing RDF by Master node only.
2021-08-30 20:27:45 WARN  BlockManager:70 - Putting block broadcast_0 failed
[WARNING]
java.lang.reflect.InaccessibleObjectException: Unable to make field private final byte[] java.lang.String.value accessible: module java.base does not "opens java.lang" to unnamed module @60572b88
    at java.lang.reflect.AccessibleObject.checkCanSetAccessible (AccessibleObject.java:357)
    at java.lang.reflect.AccessibleObject.checkCanSetAccessible (AccessibleObject.java:297)
    at java.lang.reflect.Field.checkCanSetAccessible (Field.java:177)
    at java.lang.reflect.Field.setAccessible (Field.java:171)
    at org.apache.spark.util.SizeEstimator$$anonfun$getClassInfo$3.apply (SizeEstimator.scala:335)
    at org.apache.spark.util.SizeEstimator$$anonfun$getClassInfo$3.apply (SizeEstimator.scala:329)
    at scala.collection.IndexedSeqOptimized$class.foreach (IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.ArrayOps$ofRef.foreach (ArrayOps.scala:108)
    at org.apache.spark.util.SizeEstimator$.getClassInfo (SizeEstimator.scala:329)
    at org.apache.spark.util.SizeEstimator$.visitSingleObject (SizeEstimator.scala:221)
    at org.apache.spark.util.SizeEstimator$.org$apache$spark$util$SizeEstimator$$estimate (SizeEstimator.scala:203)
    at org.apache.spark.util.SizeEstimator$.estimate (SizeEstimator.scala:70)
    at org.apache.spark.util.collection.SizeTracker$class.takeSample (SizeTracker.scala:78)
    at org.apache.spark.util.collection.SizeTracker$class.resetSamples (SizeTracker.scala:61)
    at org.apache.spark.util.collection.SizeTrackingVector.resetSamples (SizeTrackingVector.scala:25)
    at org.apache.spark.util.collection.SizeTracker$class.$init$ (SizeTracker.scala:51)
    at org.apache.spark.util.collection.SizeTrackingVector.<init> (SizeTrackingVector.scala:25)
    at org.apache.spark.storage.MemoryStore.unrollSafely (MemoryStore.scala:270)
    at org.apache.spark.storage.MemoryStore.putIterator (MemoryStore.scala:169)
    at org.apache.spark.storage.MemoryStore.putIterator (MemoryStore.scala:147)
    at org.apache.spark.storage.BlockManager.doPut (BlockManager.scala:808)
    at org.apache.spark.storage.BlockManager.putIterator (BlockManager.scala:655)
    at org.apache.spark.storage.BlockManager.putSingle (BlockManager.scala:1013)
    at org.apache.spark.broadcast.TorrentBroadcast.writeBlocks (TorrentBroadcast.scala:99)
    at org.apache.spark.broadcast.TorrentBroadcast.<init> (TorrentBroadcast.scala:85)
    at org.apache.spark.broadcast.TorrentBroadcastFactory.newBroadcast (TorrentBroadcastFactory.scala:34)
    at org.apache.spark.broadcast.BroadcastManager.newBroadcast (BroadcastManager.scala:63)
    at org.apache.spark.SparkContext.broadcast (SparkContext.scala:1326)
    at org.apache.spark.rdd.NewHadoopRDD.<init> (NewHadoopRDD.scala:75)
    at org.apache.spark.SparkContext$$anonfun$newAPIHadoopFile$2.apply (SparkContext.scala:1104)
    at org.apache.spark.SparkContext$$anonfun$newAPIHadoopFile$2.apply (SparkContext.scala:1095)
    at org.apache.spark.rdd.RDDOperationScope$.withScope (RDDOperationScope.scala:150)
    at org.apache.spark.rdd.RDDOperationScope$.withScope (RDDOperationScope.scala:111)
    at org.apache.spark.SparkContext.withScope (SparkContext.scala:714)
    at org.apache.spark.SparkContext.newAPIHadoopFile (SparkContext.scala:1095)
    at org.apache.spark.api.java.JavaSparkContext.newAPIHadoopFile (JavaSparkContext.scala:479)
    at com.merck.rdf2x.rdf.parsing.ElephasQuadParser.parseQuads (ElephasQuadParser.java:82)
    at com.merck.rdf2x.jobs.convert.ConvertJob.run (ConvertJob.java:116)
    at com.merck.rdf2x.main.Main.main (Main.java:41)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:78)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:567)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:282)
    at java.lang.Thread.run (Thread.java:831)
2021-08-30 20:27:45 ERROR ContextCleaner:95 - Error in cleaning thread
java.lang.InterruptedException
        at java.base/java.lang.Object.wait(Native Method)
        at java.base/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
        at org.apache.spark.ContextCleaner$$anonfun$org$apache$spark$ContextCleaner$$keepCleaning$1.apply$mcV$sp(ContextCleaner.scala:176)
        at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1181)
        at org.apache.spark.ContextCleaner.org$apache$spark$ContextCleaner$$keepCleaning(ContextCleaner.scala:173)
        at org.apache.spark.ContextCleaner$$anon$3.run(ContextCleaner.scala:68)
2021-08-30 20:27:45 ERROR Utils:95 - uncaught error in thread SparkListenerBus, stopping SparkContext
java.lang.InterruptedException
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1047)
        at java.base/java.util.concurrent.Semaphore.acquire(Semaphore.java:318)
        at org.apache.spark.util.AsynchronousListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(AsynchronousListenerBus.scala:66)
        at org.apache.spark.util.AsynchronousListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply(AsynchronousListenerBus.scala:65)
        at org.apache.spark.util.AsynchronousListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply(AsynchronousListenerBus.scala:65)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
        at org.apache.spark.util.AsynchronousListenerBus$$anon$1$$anonfun$run$1.apply$mcV$sp(AsynchronousListenerBus.scala:64)
        at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1181)
        at org.apache.spark.util.AsynchronousListenerBus$$anon$1.run(AsynchronousListenerBus.scala:63)
2021-08-30 20:27:45 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/metrics/json,null}
2021-08-30 20:27:45 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/stages/stage/kill,null}
2021-08-30 20:27:45 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/api,null}
2021-08-30 20:27:45 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/,null}
2021-08-30 20:27:45 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/static,null}
2021-08-30 20:27:45 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/executors/threadDump/json,null}
2021-08-30 20:27:45 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/executors/threadDump,null}
2021-08-30 20:27:45 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/executors/json,null}
2021-08-30 20:27:45 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/executors,null}
2021-08-30 20:27:45 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/environment/json,null}
2021-08-30 20:27:45 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/environment,null}
2021-08-30 20:27:45 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/storage/rdd/json,null}
2021-08-30 20:27:45 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/storage/rdd,null}
2021-08-30 20:27:45 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/storage/json,null}
2021-08-30 20:27:45 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/storage,null}
2021-08-30 20:27:45 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/stages/pool/json,null}
2021-08-30 20:27:45 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/stages/pool,null}
2021-08-30 20:27:45 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/stages/stage/json,null}
2021-08-30 20:27:45 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/stages/stage,null}
2021-08-30 20:27:45 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/stages/json,null}
2021-08-30 20:27:45 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/stages,null}
2021-08-30 20:27:45 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/jobs/job/json,null}
2021-08-30 20:27:45 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/jobs/job,null}
2021-08-30 20:27:45 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/jobs/json,null}
2021-08-30 20:27:45 INFO  ContextHandler:843 - stopped o.s.j.s.ServletContextHandler{/jobs,null}
[WARNING] thread Thread[dispatcher-event-loop-0,5,com.merck.rdf2x.main.Main] was interrupted but is still alive after waiting at least 14998msecs
[WARNING] thread Thread[dispatcher-event-loop-0,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[dispatcher-event-loop-1,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[dispatcher-event-loop-2,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[dispatcher-event-loop-3,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[dispatcher-event-loop-4,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[dispatcher-event-loop-5,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[dispatcher-event-loop-6,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[dispatcher-event-loop-7,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[dispatcher-event-loop-8,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[dispatcher-event-loop-9,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[dispatcher-event-loop-10,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[dispatcher-event-loop-11,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[shuffle-server-0,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[sparkDriverActorSystem-scheduler-1,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[sparkDriverActorSystem-akka.actor.default-dispatcher-2,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[sparkDriverActorSystem-akka.actor.default-dispatcher-3,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[sparkDriverActorSystem-akka.actor.default-dispatcher-4,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[sparkDriverActorSystem-akka.remote.default-remote-dispatcher-5,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[New I/O worker #1,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[New I/O worker #2,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[New I/O boss #3,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[New I/O worker #4,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[New I/O worker #5,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[New I/O server boss #6,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[sparkDriverActorSystem-akka.remote.default-remote-dispatcher-13,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[MAP_OUTPUT_TRACKER cleanup timer,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[BLOCK_MANAGER cleanup timer,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[BROADCAST_VARS cleanup timer,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[refresh progress,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[heartbeat-receiver-event-loop-thread,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[Timer-0,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[netty-rpc-env-timeout,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[driver-heartbeater,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[shuffle-server-0,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[SparkListenerBus,5,com.merck.rdf2x.main.Main] will linger despite being asked to die via interruption
[WARNING] NOTE: 35 thread(s) did not finish despite being asked to  via interruption. This is not a problem with exec:java, it is a problem with the running code. Although not serious, it should be remedied.
[WARNING] Couldn't destroy threadgroup org.codehaus.mojo.exec.ExecJavaMojo$IsolatedThreadGroup[name=com.merck.rdf2x.main.Main,maxpri=10]
java.lang.IllegalThreadStateException
    at java.lang.ThreadGroup.destroy (ThreadGroup.java:795)
    at org.codehaus.mojo.exec.ExecJavaMojo.execute (ExecJavaMojo.java:321)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:78)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:567)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  24.813 s
[INFO] Finished at: 2021-08-30T20:28:00+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project rdf2x: An exception occured while executing the Java class. Unable to make field private final byte[] java.lang.String.value accessible: module java.base does not "opens java.lang" to unnamed module @60572b88 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

This is strange because there's a similar [test](https://github.com/Merck/rdf2x/blob/3d5069636cf6ec0edf27cffd62b039fcb95c4386/src/test/java/com/merck/rdf2x/rdf/parsing/ElephasQuadParserTest.java#L42) which doesn't fails.

Any suggestions / ideas why is that?

**Comment by prihoda** [comment]
Hi @BoraBak sorry, this doesn't look familiar to me. This project has unfortunately not been used or maintained for a few years now, so I cannot help out with this.
